# Generated by Django 3.2.12 on 2022-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppig_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('Invoice_ID', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.PositiveIntegerField()),
                ('date_of_insertion', models.DateField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
